DECLARE
V_FNAME EMP1.FNAME%TYPE;
V_LNAME EMP1.LNAME%TYPE;
V_SALARY EMP1.SALARY%TYPE;
BEGIN
SELECT FNAME,LNAME,SALARY
INTO V_FNAME,V_LNAME,V_SALARY
FROM EMP1
WHERE SSN=12;
DBMS_OUTPUT.PUT_LINE(V_FNAME||' '||V_LNAME||' '||V_SALARY);
END;
/